version: '3'

services:
  prometheus:
    image: prom/prometheus:v2.21.0
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml

  grafana:
    depends_on:
      - prometheus
    image: grafana/grafana:9.2.4
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana

  loki:
   image: grafana/loki:2.3.0
   container_name: loki
   volumes:
     - ./loki/loki.yaml:/etc/config/loki.yaml
   entrypoint:
     - /usr/bin/loki
     - -config.file=/etc/config/loki.yaml
   ports:
     - "3100:3100"

  promtail:
    image: grafana/promtail:2.7.0
    container_name: promtail
    user: root
    volumes:
      - /var/log/nginx:/var/log/nginx
      - ./promtail/promtail-local-config.yaml:/etc/config/promtail-local-config.yaml
    entrypoint:
      - /usr/bin/promtail
      - -config.file=/etc/config/promtail-local-config.yaml
    ports:
      - "9080:9080"

  alertmanager:
    depends_on:
      - prometheus
    image: prom/alertmanager:v0.23.0
    restart: unless-stopped
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager:/etc/alertmanager
      - alertmanager-data:/data
    command: --config.file=/etc/alertmanager/alertmanager.yml --storage.path=/alertmanager

  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100
    restart: always
    deploy:
      mode: global
volumes:
  prometheus-data:

  grafana-data:

  alertmanager-data:
