groups:
  - name: DemoAlerts
    rules:
      - alert: high_load
        expr: node_load1 > 0.5
        for: 30s
        labels:
          severity: 'warning'
        annotations:
          summary: "Instance {{ $labels.instance }} under high load"
          description: "{{ $labels.instance }} of job {{ $labels.job }} is under high load."
