groups:
  - name: DemoAlerts
    rules:
      - alert: CPU-overload
        expr: sum by (cpu)(node_cpu_seconds_total{mode!="idle"}) < 50
        for: 1m

      - alert: high_load
        expr: node_load1 > 0.8
        for: 30s
        labels:
          severity: page
        annotations:
          summary: "Instance {{ $labels.instance }} under high load"
          description: "{{ $labels.instance }} of job {{ $labels.job }} is under high load."
