global:
  scrape_interval: 15s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'
  - job_name: node
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: noderam
    scrape_interval: 5s
    static_configs:
      - targets: ['44.200.133.171:9101']
alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: ['alertmanager:9093']
